import { SubCategory } from './SubCategory';
import { Users } from './Users';
import { Status } from './Status';
import { HowToSchema } from '../responsemodel/HowToSchema';
import { FaqSchema } from '../responsemodel/FaqSchema';

export class FeedContent {
    public id: string;
    public en_title: string;
    public ar_title: string;
    public hi_title: string;
    public fr_title: string;
    public en_subTitle: string;
    public ar_subTitle: string;
    public hi_subTitle: string;
    public fr_subTitle: string;
    public en_description: string;
    public ar_description: string;
    public hi_description: string;
    public fr_description: string;
    public en_metaTitle: string;
    public ar_metaTitle: string;
    public hi_metaTitle: string;
    public fr_metaTitle: string;
    public en_metaDescription: string;
    public ar_metaDescription: string;
    public hi_metaDescription: string;
    public fr_metaDescription: string;
    public en_slug: string;
    public ar_slug: string;
    public hi_slug: string;
    public fr_slug: string;
    public en_keyword: string;
    public ar_keyword: string;
    public hi_keyword: string;
    public fr_keyword: string;
    public likeCounts: number = 0;
    public readCounts: number = 0;
    public viewCounts: number = 0;
    public readingTime: number = 0;
    public wordsCount: number = 0;
    public bannerImage: string;
    public squareBanner: string;
    public landScapeBanner: string;
    public en_imageAlt: string;
    public ar_imageAlt: string;
    public hi_imageAlt: string;
    public fr_imageAlt: string;
    public en_caption: string;
    public ar_caption: string;
    public hi_caption: string;
    public fr_caption: string;
    public subCategory: SubCategory;
    public author: Users;
    public statusObj: Status;
    public canonicalUrl: string;
    public backlink: string;
    public en_howToSchema: HowToSchema;
    public en_faqSchema: Array<FaqSchema>;
    public ar_howToSchema: HowToSchema;
    public ar_faqSchema: Array<FaqSchema>;
    public fr_howToSchema: HowToSchema;
    public fr_faqSchema: Array<FaqSchema>;
    public hi_howToSchema: HowToSchema;
    public hi_faqSchema: Array<FaqSchema>;
    public isDeleted: Boolean;
    public deletedDate: Date;
    public createdDate: Date;
    public publishDate: Date;
    public updatedDate: Date;
}
