import { QuizIntro } from '../responsemodel/QuizIntro';
import { QuizFinal } from '../responsemodel/QuizFinal';
import { QuizSlide } from '../responsemodel/QuizSlide';
import { QuizResultMeter } from '../responsemodel/QuizResultMeter';
import { SubCategory } from './SubCategory';
import { Users } from './Users';
import { Status } from './Status';

export class QuizStory {
    public id: string;
    public en_title: string;
    public secondary_title: string;
    public en_metaTitle: string;
    public secondary_metaTitle: string;
    public en_metaDescription: string;
    public secondary_metaDescription: string;
    public en_slug: string;
    public secondary_slug: string;
    public en_keyword: string;
    public secondary_keyword: string;
    public canonicalUrl: string;
    public referenceLink: string;
    public en_referenceLink: string;
    public secondary_referenceLink: string;
    public bannerImage: string;
    public squareBanner: string;
    public landScapeBanner: string;
    public bannerImage_title: string;
    public squareBanner_title: string;
    public landScapeBanner_title: string;
    public image: string;
    public en_imageAlt: string;
    public secondary_imageAlt: string;
    public en_intro: Array<QuizIntro>;
    public secondary_intro: Array<QuizIntro>;
    public en_finalSlide: QuizFinal;
    public secondary_finalSlide: QuizFinal;
    public en_slides: Array<QuizSlide>;
    public secondary_slides: Array<QuizSlide>;
    public resultMeter: Array<QuizResultMeter>;
    public en_cta: string;
    public secondary_cta: string;
    public viewCounts: number = 0;
    public likeCounts: number = 0;
    public subCategory: SubCategory;
    public author: Users;
    public statusObj: Status;
    public isDeleted: Boolean;
    public deletedDate: Date;
    public createdDate: Date;
    public publishDate: Date;
    public updatedDate: Date;
}
