import { SubCategory } from './SubCategory';
import { Users } from './Users';
import { Status } from './Status';

export class Quotes {
    public id: string;
    public en_title: string;
    public secondary_title: string;
    public en_subTitle: string;
    public secondary_subTitle: string;
    public en_description: string;
    public secondary_description: string;
    public en_metaTitle: string;
    public secondary_metaTitle: string;
    public en_metaDescription: string;
    public secondary_metaDescription: string;
    public en_slug: string;
    public secondary_slug: string;
    public en_keyword: string;
    public secondary_keyword: string;
    public likeCounts: number = 0;
    public readCounts: number = 0;
    public viewCounts: number = 0;
    public en_readingTime: number = 0;
    public secondary_readingTime: number = 0;
    public en_wordCount: number = 0;
    public secondary_wordCount: number = 0;
    public bannerImage: string;
    public squareBanner: string;
    public landScapeBanner: string;
    public en_imageAlt: string;
    public secondary_imageAlt: string;
    public en_caption: string;
    public secondary_caption: string;
    public subCategory: SubCategory;
    public author: Users;
    public statusObj: Status;
    public canonicalUrl: string;
    public backlink: string;
    public isDeleted: Boolean;
    public deletedDate: Date;
    public createdDate: Date;
    public publishDate: Date;
    public updatedDate: Date;
}
