import { StorySlide } from '../responsemodel/StorySlide';
import { SubCategory } from './SubCategory';
import { Users } from './Users';
import { Status } from './Status';

export class WebStory {
    public id: string;
    public en_title: string;
    public secondary_title: string;
    public en_metaTitle: string;
    public secondary_metaTitle: string;
    public en_metaDescription: string;
    public secondary_metaDescription: string;
    public en_slug: string;
    public secondary_slug: string;
    public en_keyword: string;
    public secondary_keyword: string;
    public canonicalUrl: string;
    public referenceLink: string;
    public en_referenceLink: string;
    public secondary_referenceLink: string;
    public outBoundLink: string;
    public bannerImage: string;
    public squareBanner: string;
    public landScapeBanner: string;
    public bannerImage_title: string;
    public squareBanner_title: string;
    public landScapeBanner_title: string;
    public image: string;
    public en_imageAlt: string;
    public secondary_imageAlt: string;
    public en_slides: Array<StorySlide>;
    public secondary_slides: Array<StorySlide>;
    public en_cta: string;
    public secondary_cta: string;
    public viewCounts: number = 0;
    public likeCounts: number = 0;
    public subCategory: SubCategory;
    public author: Users;
    public statusObj: Status;
    public isDeleted: Boolean;
    public deletedDate: Date;
    public createdDate: Date;
    public publishDate: Date;
    public updatedDate: Date;
}
