import { StorySlide } from '../responsemodel/StorySlide';
import { SubCategory } from './SubCategory';
import { Users } from './Users';
import { Status } from './Status';

export class WebStory {
    public id: string;
    public en_title: string;
    public ar_title: string;
    public hi_title: string;
    public fr_title: string;
    public en_metaTitle: string;
    public ar_metaTitle: string;
    public hi_metaTitle: string;
    public fr_metaTitle: string;
    public en_metaDescription: string;
    public ar_metaDescription: string;
    public hi_metaDescription: string;
    public fr_metaDescription: string;
    public en_slug: string;
    public ar_slug: string;
    public hi_slug: string;
    public fr_slug: string;
    public en_keyword: string;
    public ar_keyword: string;
    public hi_keyword: string;
    public fr_keyword: string;
    public canonicalUrl: string;
    public referenceLink: string;
    public bannerImage: string;
    public squareBanner: string;
    public landScapeBanner: string;
    public en_imageAlt: string;
    public ar_imageAlt: string;
    public hi_imageAlt: string;
    public fr_imageAlt: string;
    public en_slides: Array<StorySlide>;
    public ar_slides: Array<StorySlide>;
    public fr_slides: Array<StorySlide>;
    public hi_slides: Array<StorySlide>;
    public en_cta: string;
    public ar_cta: string;
    public hi_cta: string;
    public fr_cta: string;
    public viewCounts: number = 0;
    public likeCounts: number = 0;
    public subCategory: SubCategory;
    public author: Users;
    public statusObj: Status;
    public isDeleted: Boolean;
    public deletedDate: Date;
    public createdDate: Date;
    public publishDate: Date;
    public updatedDate: Date;
}
